In [1]:
#1
import numpy as np
print(np.__version__)

2.0.2


In [2]:
#2
precios = np.array([24000, 28000, 22000, 30000, 8000])
print(type(precios).__name__)
print(precios.dtype)


ndarray
int64


In [4]:
#3
matriz = np.array([[2, 24000],
 [1, 28000],
 [3, 22000]])
print(matriz.shape) # forma
print(matriz.ndim) # dimensiones
print(matriz.size) # total de elementos

(3, 2)
2
6


In [6]:
#4
secuencia = np.arange(0, 10, 2)
rango = np.linspace(0, 1, 5)
ceros = np.zeros(5)

print(secuencia)
print(rango)
print(ceros.dtype)

[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]
float64


In [10]:
#5

precios = np.array([24000, 28000, 22000])

# Porque los corchetes [] indican que los números forman una sola  lista.


In [12]:
#6
cantidades = np.array([2, 1, 3, 2, 1])
precios = np.array([24000, 28000, 22000, 30000, 8000])
ingresos = cantidades * precios
print(ingresos)


[48000 28000 66000 60000  8000]


In [13]:
#7
con_descuento = precios  * 0.9
print(con_descuento)
print(con_descuento.dtype)

[21600. 25200. 19800. 27000.  7200.]
float64


In [15]:
#8

# con listas de Python
lista = [24000, 28000, 22000, 30000, 8000]
resultado = []
for p in lista:
 resultado.append(p * 1.19)
# con NumPy, en una sola línea
resultado_np = np.array(lista) * 1.19
print(resultado_np)


[28560. 33320. 26180. 35700.  9520.]


In [16]:
#9
lista = [1, 2, 3]
arreglo = np.array([1, 2, 3])
print(lista * 2)
print(arreglo * 2)


[1, 2, 3, 1, 2, 3]
[2 4 6]


In [17]:
#10
a = np.array([2, 1, 3, 2, 1])
b = np.array([10, 20, 30, 40])
print(a * b)

#para multiplicar elemento por elemento, los tamaños deben ser iguales

ValueError: operands could not be broadcast together with shapes (5,) (4,) 

In [21]:
#11
ingresos = np.zeros(5)
for i in range(5):
 ingresos[i] = cantidades[i] * precios[i]

 ingresos = cantidades * precios
print(ingresos)

[48000 28000 66000 60000  8000]


In [22]:
#12
print(precios[0]) # el primero
print(precios[-1]) # el último
print(precios[1:4]) # las posiciones 1, 2 y 3

24000
8000
[28000 22000 30000]


In [23]:
#13
mascara = precios > 20000
print(mascara)
print(precios[mascara])
print(precios[mascara].sum())


[ True  True  True  True False]
[24000 28000 22000 30000]
104000


In [26]:
#14
seleccion = precios[(precios > 10000) & (precios < 29000)]
print(seleccion)

[24000 28000 22000]


In [28]:
#15
etiquetas = np.where (precios > 25000, "alto", "normal")
print(etiquetas)


['normal' 'alto' 'normal' 'alto' 'normal']


In [31]:
#16
caros = precios[precios > 20000]
print(caros.size) # cuántos son
print(caros.sum())  # cuánto suman

4
104000


In [34]:
#17
seleccion = precios[(precios > 10000) & (precios < 29000)]
print(seleccion)

# and no nos sirve porque solo evalua dos valores como lo son falso o verdadero "&" significa AND elemento por elemento cuando trabajas con arreglos de NumPy.

In [36]:
#18
ingresos = np.array([48000, 28000, 66000, 60000, 8000])
print(ingresos.sum()) # 210000
print(ingresos.mean()) # 42000.0
print(ingresos.max()) # 66000
print(round(ingresos.std(), 2))

210000
42000.0
66000
21391.59


In [38]:
# 19
matriz = np.array([[48000, 28000],
 [66000, 60000],
 [ 8000, 12000]])
print(matriz.sum(axis=0))

[122000 100000]


In [42]:
#20
print(matriz.sum(axis=1))
print(matriz.sum())

[ 76000 126000  20000]
222000


In [44]:
#21
print(matriz.mean(axis=0))

# saca el promedio del valor de las columnas

[40666.66666667 33333.33333333]


In [97]:
datos_ventas = [
    {"fecha": "3/08/2026", "cliente_id": 101, "producto": "Bowl Andino", "categoria": "Almuerzo", "cantidad": 2, "precio_unitario": 24000, "costo_unitario": 14000, "sede": "Centro"},
    {"fecha": "3/08/2026", "cliente_id": 102, "producto": "Pasta Urbana", "categoria": "Almuerzo", "cantidad": 1, "precio_unitario": 28000, "costo_unitario": 17000, "sede": "Norte"},
    {"fecha": "4/08/2026", "cliente_id": 103, "producto": "Bowl Andino", "categoria": "Almuerzo", "cantidad": 1, "precio_unitario": 24000, "costo_unitario": 14000, "sede": "Centro"},
    {"fecha": "4/08/2026", "cliente_id": 103, "producto": "Bowl Andino", "categoria": "Almuerzo", "cantidad": 1, "precio_unitario": 24000, "costo_unitario": 14000, "sede": "Centro"},
    {"fecha": "4/08/2026", "cliente_id": 104, "producto": "Hamburguesa Central", "categoria": "Cena", "cantidad": 2, "precio_unitario": 30000, "costo_unitario": 19000, "sede": "Norte"},
]

In [110]:
#22
import pandas as pd
df_ventas=pd.read_csv('datos_ventas.csv',sep=";")#;encoding="latin1" o"ut-8"
df_ventas.head(-1)


,fecha,cliente,producto,categoria,cantidad,precio_unitario,costo_unitario,sede
0,3/08/2026,101,Bowl Andino,Almuerzo,2,"24.000,00","14.000,00",centro
1,3/08/2026,102,Pasta Urbana,Almuerzo,1,"28.000,00","17.000,00",NORTE
2,4/08/2026,103,Bowl Andino,Almuerzo,1,"24.000,00","14.000,00",Centro
3,4/08/2026,103,Bowl Andino,Almuerzo,1,"24.000,00","14.000,00",Centro
4,4/08/2026,104,Hamburguesa Central,Cena,2,"30.000,00","19.000,00",Norte
5,5/08/2026,105,Ensalada de la Casa,Almuerzo,1,"22.000,00",NaN,Centro
6,5/08/2026,101,Limonada Natural,Bebida,2,"8.000,00","2.500,00",CENTRO
7,6/08/2026,106,Pasta Urbana,Almuerzo,2,"28.000,00","17.000,00",norte
8,6/08/2026,106,Pasta Urbana,Almuerzo,2,"28.000,00","17.000,00",norte
9,7/08/2026,107,Bowl Andino,Almuerzo,3,"24.000,00","14.000,00",Centro


In [108]:
df_ventas = pd.read_csv('datos_ventas.csv', sep=';')
df_ventas["fecha"] = pd.to_datetime(df_ventas["fecha"])

print(df_ventas.shape)  # forma de la tabla
print(df_ventas.head(3))  # primeras tres filas

KeyError: 'fecha'

In [113]:
23#
una = df_ventas["producto"]
varias =  df_ventas[["producto", "cantidad"]]
print(type(una).__name__, type(varias).__name__)

Series DataFrame


In [114]:
#24
arreglo = df_ventas["cantidad"].to_numpy()
print(type(arreglo).__name__)
print(arreglo.sum())

ndarray
32


In [115]:
#25
print(df_ventas.loc[0:2].shape[0])
print(df_ventas.iloc[0:2].shape[0])


3
2


In [116]:
#26
mascara = (
    (df_ventas["sede"] == "Centro")
    & (df_ventas["categoria"] == "Almuerzo")
)

seleccion = df_ventas.loc[mascara].copy()

print(seleccion.shape[0], seleccion["cantidad"].sum())

3 7


In [117]:
#27
# Convert 'precio_unitario' and 'costo_unitario' to numeric, handling the decimal/thousands separators
df_ventas["precio_unitario"] = df_ventas["precio_unitario"].astype(str).str.replace('.', '', regex=False).str.replace(',', '.').astype(float)
df_ventas["costo_unitario"] = df_ventas["costo_unitario"].astype(str).str.replace('.', '', regex=False).str.replace(',', '.').astype(float)

df_ventas["ingreso"] = df_ventas["cantidad"] * df_ventas["precio_unitario"]
df_ventas["costo_total"] = df_ventas["cantidad"] * df_ventas["costo_unitario"]
df_ventas["margen_bruto"] = df_ventas["ingreso"] - df_ventas["costo_total"]

print(df_ventas["ingreso"].sum(), df_ventas["margen_bruto"].sum())

TypeError: unsupported operand type(s) for -: 'str' and 'str'